name: Luacheck Example
on: [push, pull_request]
jobs:
  sile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      # - name: Control output (should fail)
      #   uses: lunarmodules/luacheck@v1.1.2
      # - name: Full output (should fail)
      #   uses: lunarmodules/luacheck@v1.1.2
      #   with:
      #       args: . --config full.luacheck
      - name: Errors only output (should pass)
        uses: lunarmodules/luacheck@v1.1.2
        with:
            args: . --config errors.luacheck
